In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf 

In [2]:
# create a constant
a = tf.constant(5.0)
b = tf.constant(10.0)

# variable
x = tf.Variable(3.0)

result = a * x + b

print('Result of a * x + b is :', result)

Result of a * x + b is : tf.Tensor(25.0, shape=(), dtype=float32)


In [3]:
# update variable 
x.assign(5.0)
new_result = a * x + b

print('Result of a * x + b is :', new_result.numpy() )

Result of a * x + b is : 35.0


In [4]:
# createa a tensor
a = tf.constant([3, 3, 3])
b = tf.constant([2, 2, 2])


In [5]:
# import tensorflow.compat.v1 as tf

# tf.disable_v2_behavior()
# tf.disable_eager_execution()

# x = tf.placeholder(dtype=tf.float32, shape=None)

In [7]:
# Create another tenseor .. Constant
a = tf.constant(5.0)
b = tf.constant(10.0)

result = a * x + b

# create a session
# with tf.Session() as sess:
#     result_value = sess.run(result, feed_dict = {x:3})
#     print('Result with placeholder is :', result_value)

In [8]:
# operations
sum_result = tf.add(a, b)        # Addition
diff_result = tf.subtract(a, b)  # Subtraction
quot_result = tf.divide(a, b)    # Division
prod_result = tf.multiply(a, b)  # Multiplication

# print results
print("Sum of Tensors:", sum_result)
print("Difference of tensors:", diff_result)
print("Quotient of Tensor:", quot_result)
print("Product of tensors:", prod_result)

Sum of Tensors: tf.Tensor(15.0, shape=(), dtype=float32)
Difference of tensors: tf.Tensor(-5.0, shape=(), dtype=float32)
Quotient of Tensor: tf.Tensor(0.5, shape=(), dtype=float32)
Product of tensors: tf.Tensor(50.0, shape=(), dtype=float32)


In [9]:
# Element wise
min_result = tf.minimum(a, b)
max_result = tf.maximum(a, b)
abs_result = tf.abs(a)

print('Minimum', min_result)
print('Maximum', max_result)
print('Absolute Value', abs_result)

Minimum tf.Tensor(5.0, shape=(), dtype=float32)
Maximum tf.Tensor(10.0, shape=(), dtype=float32)
Absolute Value tf.Tensor(5.0, shape=(), dtype=float32)


In [10]:
c = tf.constant([-1, -2, 1])
tf.abs(c)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 1], dtype=int32)>

In [11]:
# change a from int to float
a = tf.cast(a, dtype = tf.float32)
a

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [12]:
log_result = tf.math.log(tf.maximum(a, 1e-8))
exp_result = tf.exp(a)

print('Logarithm', log_result)
print('Exponential', exp_result)

Logarithm tf.Tensor(1.609438, shape=(), dtype=float32)
Exponential tf.Tensor(148.41316, shape=(), dtype=float32)


In [13]:
a = tf.constant([3,3,3])

scalar = tf.constant(2)
broadcast_result = tf.add(a, scalar)

print('Broadcast Result', broadcast_result)

Broadcast Result tf.Tensor([5 5 5], shape=(3,), dtype=int32)


In [14]:
sum_axis = tf.reduce_sum(a, axis=0)   # Sum across the first axis
mean_axis = tf.reduce_mean(a, axis=0) # Mean across the second axis

print("Sum across axis 0:", sum_axis)
print("Mean across axis 0:", mean_axis)

Sum across axis 0: tf.Tensor(9, shape=(), dtype=int32)
Mean across axis 0: tf.Tensor(3, shape=(), dtype=int32)


In [15]:
# create a tensor with shape [2,2]
input_data = tf.constant([[1.0, 2.0], [3.0, 4.0]])
weights = tf.constant([[0.5, -1.0], [1.0, 2.0]]) # weights are randomly generated 

# Matrix multiplication
output = tf.matmul(input_data, weights)
print('Neural Network Layer Output:\n', output)

Neural Network Layer Output:
 tf.Tensor(
[[2.5 3. ]
 [5.5 5. ]], shape=(2, 2), dtype=float32)


In [16]:
# simulating image pixel values
image = tf.constant([[255,128], [64,32]], dtype=tf.float32) # shape [2,2]
scaling_factor = 0.5
scaled_image = tf.multiply(image, scaling_factor)
print('SCaled Image:\n', scaled_image)

SCaled Image:
 tf.Tensor(
[[127.5  64. ]
 [ 32.   16. ]], shape=(2, 2), dtype=float32)


In [17]:
import tensorflow as tf

# Example: Simulating a sequence of words (embeddings)
sequence = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])  # Shape: (2, 3)

# Attention scores (one for each word in the sequence)
attention_scores = tf.constant([[0.1, 0.5, 0.4], [0.6, 0.2, 0.2]])  # Shape: (2, 3)

# Apply attention weights using element-wise multiplication
weighted_sequence = tf.multiply(sequence, attention_scores)

print("Weighted Sequence:\n", weighted_sequence)

Weighted Sequence:
 tf.Tensor(
[[0.1 1.  1.2]
 [2.4 1.  1.2]], shape=(2, 3), dtype=float32)


In [18]:
x = tf.Variable(1.0)
def f(x):
    y = x**2 + 2*x -5
    return y

In [19]:
# Gradiant tape used for derivatives
with tf.GradientTape() as tape:
    y = f(x)
g_x = tape.gradient(y,x)
g_x    

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [20]:
import time

# Create large random matrices
size = 10000
np_matrix_a = np.random.randn(size, size)
np_matrix_b = np.random.randn(size, size)
tf_matrix_a = tf.random.normal((size, size))
tf_matrix_b = tf.random.normal((size, size))

# Benchmark NumPy
start_time = time.time()
np_result = np.dot(np_matrix_a, np_matrix_b)
np_duration = time.time() - start_time

# Benchmark TensorFlow on CPU
start_time = time.time()
tf_result = tf.multiply(tf_matrix_a, tf_matrix_b)
tf_duration = time.time() - start_time

print("NumPy Duration: {:.6f} seconds".format(np_duration))
print("TensorFlow (CPU) Duration: {:.6f} seconds".format(tf_duration))

NumPy Duration: 70.887211 seconds
TensorFlow (CPU) Duration: 16.240735 seconds


In [21]:

# Example forward propagation in Python
def forward_propagation(X, W, b):
    Z = np.dot(W, X) + b        # Weighted sum
    A = 1 / (1 + np.exp(-Z))    # Sigmoid activation function
    return A

# Dummy data
X = np.array([[1.0], [2.0], [3.0]])     # Input
W = np.array([[0.2, 0.4, 0.6]])         # Weights
b = np.array([[0.5]])                   # Bias

# Forward propagation
output = forward_propagation(X, W, b)
print("Output of forward propagation:", output)

Output of forward propagation: [[0.96442881]]


In [22]:

# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# ReLU activation function
def relu(x):
    return np.maximum(0, x)

# Tanh activation function
def tanh(x):
    return np.tanh(x)

# Example of activation functions
x = np.array([-1.0, 0.0, 1.0, 2.0])

print("Sigmoid:", sigmoid(x))
print("ReLU:", relu(x))
print("Tanh:", tanh(x))

Sigmoid: [0.26894142 0.5        0.73105858 0.88079708]
ReLU: [0. 0. 1. 2.]
Tanh: [-0.76159416  0.          0.76159416  0.96402758]


In [23]:
def forward_with_activation(X, W, b, activation_function):
    Z = np.dot(W, X) + b  # Weighted sum
    
    match activation_function:
        case 'sigmoid':
            A = sigmoid(Z)
        case 'relu':
            A = relu(Z)
        case 'tanh':
            A = tanh(Z)
    
    return A

# Testing the function
W = np.array([[0.2, 0.4, 0.6]])
b = np.array([[0.5]])
X = np.array([[1.0], [2.0], [3.0]])

output = forward_with_activation(X, W, b, activation_function='relu')
print("Output with RELU activation:", output)

Output with RELU activation: [[3.3]]


In [24]:
output = forward_with_activation(X, W, b, activation_function='sigmoid')
print("Output with RELU activation:", output)

Output with RELU activation: [[0.96442881]]
